vich_uploader:
    db_driver: orm

    mappings:
        posters:
            uri_prefix: /images/posters
            upload_destination: '%kernel.project_dir%/public/images/posters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

